<AuditFile xmlns="urn:OECD:StandardAuditFile-Tax:AO:1.01_01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Header>
    <AuditFileVersion>1.01_01</AuditFileVersion>
    <CompanyID>{{COMPANY_VAT}}</CompanyID>
    <TaxRegistrationNumber>{{COMPANY_VAT}}</TaxRegistrationNumber>
    <CompanyName>{{COMPANY_NAME}}</CompanyName>
    <BusinessName>{{COMPANY_NAME}}</BusinessName>
    <CompanyAddress>
      <AddressDetail>{{COMPANY_ADDRESS}}</AddressDetail>
      <City>{{COMPANY_CITY}}</City>
      <Country>AO</Country>
    </CompanyAddress>
    <FiscalYear>{{INVOICE_YEAR}}</FiscalYear>
    <StartDate>{{INVOICE_DATE}}</StartDate>
    <EndDate>{{INVOICE_DATE}}</EndDate>
    <CurrencyCode>{{CURRENCY_CODE}}</CurrencyCode>
    <DateCreated>{{INVOICE_DATE}}</DateCreated>
    <TaxEntity>Global</TaxEntity>
    <ProductCompanyID>{{SOFTWARE_NAME}}</ProductCompanyID>
    <ProductID>{{SOFTWARE_NAME}}/{{CERTIFICATE_NO}}</ProductID>
    <ProductVersion>1.0</ProductVersion>
    <SoftwareCertificateNumber>{{CERTIFICATE_NO}}</SoftwareCertificateNumber>
  </Header>
  <MasterFiles>
    <Customer>
      <CustomerID>{{CUSTOMER_ID}}</CustomerID>
      <AccountID>Desconhecido</AccountID>
      <CustomerTaxID>{{CUSTOMER_VAT}}</CustomerTaxID>
      <CompanyName>{{CUSTOMER_NAME}}</CompanyName>
      <BillingAddress>
        <AddressDetail>{{CUSTOMER_ADDRESS}}</AddressDetail>
        <City>{{CUSTOMER_CITY}}</City>
        <Country>AO</Country>
      </BillingAddress>
      <SelfBillingIndicator>0</SelfBillingIndicator>
    </Customer>
  </MasterFiles>
  <SourceDocuments>
    <SalesInvoices>
      <NumberOfEntries>1</NumberOfEntries>
      <TotalDebit>0.00</TotalDebit>
      <TotalCredit>{{INVOICE_TOTAL}}</TotalCredit>
      <Invoice>
        <InvoiceNo>{{INVOICE_NUMBER}}</InvoiceNo>
        <DocumentStatus>
          <InvoiceStatus>N</InvoiceStatus>
          <InvoiceStatusDate>{{INVOICE_DATE}}T00:00:00</InvoiceStatusDate>
          <SourceID>{{STAFF_ID}}</SourceID>
          <SourceBilling>P</SourceBilling>
        </DocumentStatus>
        <Hash>{{HASH}}</Hash>
        <HashControl>{{HASH_CONTROL}}</HashControl>
        <Period>1</Period>
        <InvoiceDate>{{INVOICE_DATE}}</InvoiceDate>
        <InvoiceType>FT</InvoiceType>
        <SpecialRegimes>
          <SelfBillingIndicator>0</SelfBillingIndicator>
          <CashVATSchemeIndicator>0</CashVATSchemeIndicator>
          <ThirdPartiesBillingIndicator>0</ThirdPartiesBillingIndicator>
        </SpecialRegimes>
        <SourceID>{{STAFF_ID}}</SourceID>
        <SystemEntryDate>{{INVOICE_DATE}}T00:00:00</SystemEntryDate>
        <CustomerID>{{CUSTOMER_ID}}</CustomerID>
        {{#LINE_ITEMS}}
        <Line>
          <LineNumber>{{LINE_NUMBER}}</LineNumber>
          <ProductCode>{{ITEM_ID}}</ProductCode>
          <ProductDescription>{{ITEM_DESCRIPTION}}</ProductDescription>
          <Quantity>{{ITEM_QTY}}</Quantity>
          <UnitOfMeasure>Unidade</UnitOfMeasure>
          <UnitPrice>{{ITEM_RATE}}</UnitPrice>
          <TaxPointDate>{{INVOICE_DATE}}</TaxPointDate>
          <Description>{{ITEM_DESCRIPTION}}</Description>
          <DebitAmount>0.00</DebitAmount>
          <CreditAmount>{{ITEM_TOTAL}}</CreditAmount>
          <Tax>
            <TaxType>IVA</TaxType>
            <TaxCountryRegion>AO</TaxCountryRegion>
            <TaxCode>NOR</TaxCode>
            <TaxPercentage>14.00</TaxPercentage>
          </Tax>
          <SettlementAmount>0.00</SettlementAmount>
        </Line>
        {{/LINE_ITEMS}}
        <DocumentTotals>
          <TaxPayable>{{INVOICE_TOTAL_TAX}}</TaxPayable>
          <NetTotal>{{INVOICE_SUBTOTAL}}</NetTotal>
          <GrossTotal>{{INVOICE_TOTAL}}</GrossTotal>
        </DocumentTotals>
      </Invoice>
    </SalesInvoices>
  </SourceDocuments>
</AuditFile>
